# it is not really Python, but there is no R support on Travis CI yet
language: python

sudo: false

services:
  - docker
  - mongodb

addons:
  apt:
    packages:
      - python-virtualenv
      - gfortran

cache:
  directories:
    - $HOME/local
    - $HOME/vtk-precise64
    - $HOME/cmake-3.2.2-Linux-x86_64

# environment variables
env:
  - PYTHONPATH=~/vtk-precise64/lib/python2.7/site-packages:~/vtk-precise64/lib LD_LIBRARY_PATH=~/vtk-precise64/lib:~/local/lib:~/local/lib/R/lib

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

before_install:
  - pip install -U pip six
  - pushd "${HOME}"
  - if [ ! -f $HOME/cmake-3.2.2-Linux-x86_64/bin/cmake ] ; then  curl -L http://cmake.org/files/v3.2/cmake-3.2.2-Linux-x86_64.tar.gz | gunzip -c | tar x ; fi
  - cd cmake-*/bin && export PATH="${PWD}:${PATH}"
  - popd
  - cmake --version
  # download VTK
  - if [ ! -f $HOME/vtk-precise64/bin/vtkpython ] ; then curl -L https://data.kitware.com/api/v1/file/588b62958d777f4f3f30c773/download | tar zx -C ~ ; fi
  # install R
  - mkdir -p $HOME/local
  - if [ ! -f $HOME/local/env-arbor ] ; then curl -L https://data.kitware.com/api/v1/file/588b63c68d777f4f3f30c776/download | tar jx -C $HOME/local/ ; mv $HOME/local/env $HOME/local/env-arbor ; fi
  - source $HOME/local/env-arbor
  - R --version
  - R -e '.libPaths(); sessionInfo()'

# install dependencies
install:
  # install Python packages for core and all plugins
  - python scripts/install_requirements.py --mode=dev --all

# run tests
script:
  - mkdir _build
  - cd _build
  - cmake -D PYTHON_COVERAGE:BOOL=ON  ..
  - ctest -VV -S ../cmake/travis_continuous.cmake || true
  - if [ -f test_failed ] ; then false ; fi
  - cd ..

after_success:
  - coveralls
