version: 2
jobs:
  integration_tests:
    machine: true
    working_directory: /home/circleci/project
    steps:
      - add_ssh_keys:
          fingerprints:
            - "50:b7:1d:44:fd:c4:f4:06:9a:4c:0f:16:0c:e1:3b:91"
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            pip install docker-compose
      - run:
          name: Get the environment up and running with Docker Compose
          command: |
            cd tests/integration && make && make run

      - run:
          name: Run integration tests
          command: |
            cd tests/integration && make test

      - run:
          name: Dump girder docker logs
          command: |
            cd tests/integration && docker-compose logs girder
          when: on_fail

      - run:
          name: Dump girder_worker docker logs
          command: |
            cd tests/integration && docker-compose logs girder_worker
          when: on_fail

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                ./scripts/galaxy_deploy.sh
            fi

  py2_unit_tests:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run:
          name: Setup virtual environment
          command: |
            if [ ! -d girder_env ]; then virtualenv girder_env; fi
            echo ". $CIRCLE_WORKING_DIRECTORY/girder_env/bin/activate" >> $BASH_ENV
      - run:
          name: Install CI dependencies
          command: pip install codecov tox
      - run:
          name: Run unit tests
          command: tox -e py27
      - run:
          name: Upload coverage to codecov
          command: coverage combine && codecov

  py3_unit_tests:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Setup virtual environment
          command: |
            if [ ! -d girder_env ]; then python3 -m venv girder_env; fi &&
            echo ". $CIRCLE_WORKING_DIRECTORY/girder_env/bin/activate" >> $BASH_ENV
      - run:
          name: Install CI dependencies
          command: pip install codecov tox
      - run:
          name: Run unit tests
          command: tox -e py36
      - run:
          name: Upload coverage to codecov
          command: coverage combine && codecov

  lint:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run:
          name: Create virtual environment (if necessary)
          command: if [ ! -d girder_env ]; then virtualenv girder_env; fi
      - run:
          name: Activate virtual environment
          command: echo ". $CIRCLE_WORKING_DIRECTORY/girder_env/bin/activate" >> $BASH_ENV
      - run:
          name: Install tox
          command: pip install tox
      - run:
          name: Run linting tests
          command: tox -e lint

workflows:
  version: 2
  ci:
    jobs:
      - py2_unit_tests
      - py3_unit_tests
      - integration_tests
      - lint
