version: 2
jobs:
  build:
    machine: true
    working_directory: /home/circleci/project
    steps:
      - add_ssh_keys:
          fingerprints:
            - "50:b7:1d:44:fd:c4:f4:06:9a:4c:0f:16:0c:e1:3b:91"
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            pip install docker-compose
      - run:
          name: Get the environment up and running with Docker Compose
          command: |
            cd tests/integration && make && make run

      - run:
          name: Run integration tests
          command: |
            cd tests/integration && make test

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                ./scripts/galaxy_deploy.sh
            fi
